# @package _global_

defaults:
  - _self_
  - data: latent_dino_kitti_vio # choose datamodule with `test_dataloader()` for evaluation
  - model: latent_vio_mvformer # choose model with `test_step()` for evaluation
  - logger: null
  - paths: default
  - extras: default
  - hydra: default
  - trainer: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
